[FIX] Configuration
Guess the defaultvalue was added after isRequired and don't need to be maintained

InvalidConfigurationException: The child node "container_types" at path "sonata_block.profiler" must be configured.